# Generated by Django 4.2.7 on 2024-04-08 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FolderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fileName', models.CharField(max_length=200)),
                ('file', models.ImageField(upload_to='files/')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('folderParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FolderApp.foldermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
